runtime: nodejs14

automatic_scaling:
  min_instances: 0
  max_instances: 1

handlers:
  - url: /*
    static_dir: client/build/index.html

  - url: /*
    static_files: client/build/index.html
    upload: client/build/index.html
